version: "3.8"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: phonebook_db
            MYSQL_USER: devalps
            MYSQL_PASSWORD: devalps123
        volumes:
            - db-data:/var/lib/mysql
        configs:
            - source: table
              target: /docker-entrypoint-initdb.d/init.sql
        networks:
            - PBnet
    app-server:
        image: 133446465665.dkr.ecr.us-east-1.amazonaws.com/project/phonebook-app:latest
        deploy:
            mode: global
            update_config:
                parallelism: 2
                delay: 5s
                order: start-first
        ports:
            - "80:80"
        networks:
            - PBnet
networks:
    PBnet:
        driver: overlay

volumes:
    db-data:

configs:
    table:
        file: ./init.sql